(() => {
  "use strict";
  const cfg = window.birthdayConfig || {
    herName: "HER NAME",
    nickname: "NICKNAME",
    birthday: "YYYY-MM-DD",
    finalMessage: "I hope this year becomes your favourite chapter yet.",
    nextBirthdayMessage: "[Write the message that unlocks on her next birthday]",
    vault: { code: "143", clues: ["[Add a clue]", "[Add an inside joke]", "[Add one more clue]"] },
    cake: { flavours: ["Red Velvet", "Black Forest", "Chocolate Truffle", "Strawberry", "Vanilla", "Butterscotch"] },
    audio: { birthdaySong: "assets/music/birthday-song.mp3" },
    secretMessages: ["[Write something you genuinely admire about her]"]
  };
  const stage = document.getElementById("scene-stage");
  const loading = document.getElementById("loading-screen");
  const bar = document.getElementById("loading-bar");
  const label = document.getElementById("loading-label");
  const toast = document.getElementById("toast");
  const sceneCode = document.getElementById("scene-code");
  const audioToggle = document.getElementById("audio-toggle");
  const storageKey = "birthday-mission-progress";
  const sceneNames = ["Invitation", "Love notes", "Cake and wish", "Balloons", "Letter", "Birthday banner"];
  const palette = ["vanilla", "red-velvet", "forest", "chocolate", "strawberry", "butterscotch"];
  let progress = loadProgress();
  let scene = Math.min(progress.scene || 0, 5);
  let audioContext;
  let activeAudio;
  let micStream;
  let micFrame;
  let balloonIndex = 0;
  let cakeSelections = progress.cakeSelections || [0, 1, 2, 3];

  function loadProgress() {
    try { return JSON.parse(localStorage.getItem(storageKey)) || {}; } catch (_) { return {}; }
  }
  function saveProgress() {
    try { localStorage.setItem(storageKey, JSON.stringify({ ...progress, scene, cakeSelections })); } catch (_) { /* Storage is optional. */ }
  }
  function esc(value) { return String(value).replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char])); }
  function formatMessage(value) { return esc(value).replace(/\n/g, "<br>"); }
  function name() { return esc(cfg.herName); }
  function toastMessage(message) { toast.textContent = message; toast.classList.add("show"); window.setTimeout(() => toast.classList.remove("show"), 2800); }
  function button(label, action, extra = "") { return `<button class="button ${extra}" data-action="${action}" type="button">${label}</button>`; }
  function updateHud() { if (sceneCode) sceneCode.textContent = `${String(scene + 1).padStart(2, "0")} / 06`; }
  function stopMusic() { if (activeAudio) { activeAudio.pause(); activeAudio.currentTime = 0; activeAudio = null; } }
  function go(next) { if (next === 7) next = 4; if (next === 8) next = 5; if (next === 9) next = 5; stopMicrophone(); stopMusic(); scene = next; progress.scene = next; saveProgress(); stage.classList.remove("scene-enter"); void stage.offsetWidth; stage.classList.add("scene-enter"); updateHud(); render(); }
  function setupAudio() {
    try { audioContext = audioContext || new (window.AudioContext || window.webkitAudioContext)(); if (audioContext.state === "suspended") audioContext.resume(); } catch (_) { audioContext = null; }
  }
  function playTone(frequency = 440, duration = 0.12) {
    if (!audioContext) return;
    try { const oscillator = audioContext.createOscillator(); const gain = audioContext.createGain(); oscillator.frequency.value = frequency; gain.gain.setValueAtTime(0.04, audioContext.currentTime); gain.gain.exponentialRampToValueAtTime(0.001, audioContext.currentTime + duration); oscillator.connect(gain).connect(audioContext.destination); oscillator.start(); oscillator.stop(audioContext.currentTime + duration); } catch (_) { /* Sound is decorative. */ }
  }
  function playMusic(src, loop = false) {
    if (!src) return;
    if (activeAudio) { activeAudio.pause(); activeAudio = null; }
    activeAudio = new Audio(src); activeAudio.loop = loop; activeAudio.volume = 0.22; activeAudio.addEventListener("error", () => toastMessage("The music file is not here yet, but the mission continues."), { once: true }); activeAudio.play().catch(() => {});
  }
  function stopMicrophone() { if (micFrame) cancelAnimationFrame(micFrame); micFrame = null; if (micStream) micStream.getTracks().forEach(track => track.stop()); micStream = null; }
  function render() {
    const views = [renderIntro, renderIdentity, renderCake, renderBalloons, renderLetter, renderFinale];
    (views[scene] || renderIntro)();
  }
  function renderIntro() {
    stage.innerHTML = `<section class="scene intro-scene"><div class="scene-copy reveal"><p class="eyebrow">A little birthday secret</p><h1>Today is<br><em>all about you.</em></h1><p class="lede">Someone very loved was born today, and I made you a tiny world to wander through.</p><div class="subject-line"><span>For</span><strong>${name()}</strong><span>From</span><strong>Someone who loves you</strong></div>${button("Open your surprise", "accept", "button-gold")}<p class="fine-print">Best experienced with sound on · <span aria-hidden="true">♡</span></p></div><figure class="intro-photo"><img src="${esc(cfg.photos[0])}" alt="A favourite memory of ${name()}" onerror="this.style.display='none'"><figcaption>one of my favourite people</figcaption></figure><div class="orbit-mark" aria-hidden="true"><i></i><i></i><i></i></div></section>`;
  }
  function renderIdentity() {
    const notes = typeof loveNotes !== "undefined" ? loveNotes : ["You make ordinary days feel special."];
    stage.innerHTML = `<section class="scene centered-scene love-notes-scene"><p class="eyebrow">A little something for you</p><h2>Three things I<br><em>hope you know.</em></h2><p class="lede">Tap each note slowly. They are small, but they are true.</p><div class="love-note-stack">${notes.map((note, index) => `<button class="love-note" type="button" data-action="love-note" data-index="${index}"><span>♡</span><strong>${esc(note.title)}</strong><small>${esc(note.body)}</small></button>`).join("")}</div>${button("Continue to your cake", "continue-identity", "button-gold")}</section>`;
  }
  function renderIdentityConfirmed() {
    stage.innerHTML = `<section class="scene centered-scene"><p class="eyebrow">Signal matched</p><div class="seal">✓</div><h2>Identity<br><em>confirmed</em></h2><p class="lede">Yep. Definitely ${name()}.</p>${button("Continue mission", "continue-identity", "button-gold")}</section>`;
  }
  function renderMemories() {
    const discovered = progress.memories || [];
    stage.innerHTML = `<section class="scene"><div class="scene-heading"><div><p class="eyebrow">02 · Coordinates recovered</p><h2>Recover the missing <em>memories</em></h2><p class="lede">Some moments were scattered across the universe. Find them.</p></div><span class="counter">${discovered.length} / ${missionMemories.length}</span></div><div class="constellation">${missionMemories.map((memory, index) => `<button class="star-node ${discovered.includes(index) ? "found" : ""}" style="--x:${18 + ((index * 19) % 68)}%;--y:${18 + ((index * 29) % 62)}%" data-action="memory" data-index="${index}" aria-label="Open memory ${index + 1}"><span></span></button>`).join("")}<div class="constellation-line"></div></div><div class="memory-prompt"><p>${discovered.length < 1 ? "Recover one signal to unlock the next coordinate. There are more stars if you want to explore." : "The path ahead is open. You can keep exploring or continue."}</p>${button(discovered.length < 1 ? "Explore the stars" : "Enter the vault", discovered.length < 1 ? "hint" : "continue-memories", "button-gold")}</div></section>`;
  }
  function renderVault() {
    stage.innerHTML = `<section class="scene vault-scene"><p class="eyebrow">03 · Secure archive</p><h2>The birthday <em>vault</em></h2><p class="lede">Something is waiting inside.</p><div class="vault"><div class="vault-door"><div class="vault-lock">${(progress.vaultInput || "···").split("").map(digit => `<b>${esc(digit)}</b>`).join("")}</div><span class="vault-label">BIRTHDAY ARCHIVE</span></div></div><div class="clues">${cfg.vault.clues.map((clue, index) => `<button type="button" class="clue" data-action="clue" data-index="${index}"><span>0${index + 1}</span>Clue</button>`).join("")}</div><div class="keypad">${[1,2,3,4,5,6,7,8,9,"⌫",0,"↵"].map(key => `<button type="button" data-action="key" data-key="${key}">${key}</button>`).join("")}</div><p class="feedback">${esc(progress.vaultFeedback || "Three digits. No pressure, agent.")}</p></section>`;
  }
  function renderCake() {
    stage.innerHTML = `<section class="scene cake-scene centered-scene"><p class="eyebrow">A wish made just for you</p><h2>Close your eyes.<br><em>Make a wish.</em></h2><p class="lede">The cake is ready. When you are ready, blow the candles out right here.</p><div class="round-cake-preview"><div class="cake-topper">HAPPY<br>BIRTHDAY<br><strong>${name()}</strong></div><div class="cake-candles flames">${[1,2,3,4].map(() => `<i><b></b></i>`).join("")}</div><img class="real-cake" src="assets/images/birthday-cake.svg" alt="A beautiful birthday cake for ${name()}"><div class="cake-plate"></div></div><p class="wish-instruction">Think of one lovely thing you want this year. Keep it secret.</p><p class="mic-status">Nothing is recorded or uploaded.</p>${button("Enable microphone", "enable-mic", "button-gold")}${button("Tap to blow", "tap-blow", "button-quiet")}</section>`;
  }
  function renderWish() {
    stage.innerHTML = `<section class="scene wish-scene"><p class="eyebrow">05 · A quiet moment</p><h2>Before we <em>continue...</em></h2><div class="wish-copy"><p>Close your eyes.</p><p>Think of one wish.</p><p>Don't tell anyone.</p></div><div class="wish-cake"><div class="flames">${[1,2,3,4].map(() => `<i></i>`).join("")}</div><div class="cake-mini"></div></div>${button("I've made my wish", "wish-made", "button-gold")}</section>`;
  }
  function renderBlowPrompt() {
    stage.innerHTML = `<section class="scene centered-scene"><p class="eyebrow">Wish registered</p><h2>Now blow out<br><em>your candles.</em></h2><p class="lede">Your microphone is used only to detect the blow. Nothing is recorded or sent anywhere.</p><p class="mic-status">To make this work, your browser needs microphone access.</p>${button("Enable microphone", "enable-mic", "button-gold")}${button("Tap to blow", "tap-blow", "button-quiet")}</section>`;
  }
  function renderCelebration() {
    stage.innerHTML = `<section class="scene celebration-scene centered-scene"><div class="celebration-burst" aria-hidden="true"></div><div class="confetti" aria-hidden="true">${Array.from({ length: 28 }, (_, index) => `<i style="--i:${index}"></i>`).join("")}</div><p class="eyebrow">Wish registered ✓</p><h1>It is your day,<br><em>${name()}!</em></h1><p class="lede">May every good thing find its way to you.</p>${button("Pop some happy balloons", "start-balloons", "button-gold")}</section>`;
  }
  function renderBalloons() {
    const opened = progress.balloons || [];
    stage.innerHTML = `<section class="scene balloons-scene"><p class="eyebrow">A pocketful of happiness</p><h2>Pop the birthday <em>balloons</em></h2><p class="lede">Each one has a little love note inside.</p><div class="balloon-field">${balloonMessages.map((message, index) => `<button type="button" class="balloon balloon-${index}" data-action="balloon" data-index="${index}" aria-label="Pop birthday balloon ${index + 1}"><span>${opened.includes(index) ? "♥" : ""}</span></button>`).join("")}</div><p class="counter">${opened.length} / ${balloonMessages.length} love notes opened</p>${button(opened.length >= balloonMessages.length ? "Continue to the letter" : "Pop a balloon", opened.length >= balloonMessages.length ? "continue-balloons" : "hint", opened.length >= balloonMessages.length ? "button-gold" : "button-quiet")}</section>`;
  }
  function renderLetter() {
    stage.innerHTML = `<section class="scene letter-scene"><p class="eyebrow">A quiet little letter</p><h2>Some feelings are better<br>when they are <em>written.</em></h2><p class="lede">This one is only for you.</p><div class="envelope"><div class="envelope-flap"></div><div class="envelope-mark">For ${name()} ♡</div></div>${button("Open my letter", "open-letter", "button-gold")}</section>`;
  }
  function renderOpenedLetter() {
    stage.innerHTML = `<section class="scene letter-page"><p class="eyebrow">A note for ${name()}</p><article class="letter-content">${birthdayLetter.map((paragraph, index) => `<p class="letter-line" data-letter-index="${index}"></p>`).join("")}</article>${button("Continue", "continue-letter", "button-gold")}</section>`;
    playMusic(cfg.audio.letter, true);
    birthdayLetter.forEach((paragraph, index) => { window.setTimeout(() => { const line = document.querySelector(`[data-letter-index="${index}"]`); if (line) { line.textContent = paragraph.replace("[nickname]", cfg.nickname); line.classList.add("written"); } }, 350 + index * 650); });
  }
  function renderSong() {
    stage.innerHTML = `<section class="scene song-scene"><p class="eyebrow">08 · Personal transmission</p><h2>I made something <em>for you.</em></h2><p class="lede">You probably weren't expecting this. Put your headphones on.</p><div class="record"><div class="record-label">${name()}<small>birthday edition</small></div></div><div class="song-player"><button type="button" class="play-button" data-action="play-song" aria-label="Play your song">▶</button><div class="song-track"><span>YOUR SONG</span><input type="range" min="0" max="100" value="0" data-action="song-seek" aria-label="Song progress"><small id="song-time">00:00 / --:--</small></div><div class="equalizer" aria-hidden="true">▂▅▃▇▂▆▃</div></div><p id="song-status" class="feedback"></p>${button("Continue", "continue-song", "button-quiet")}</section>`;
  }
  function renderFinale() {
    stage.innerHTML = `<section class="scene finale-scene"><p class="eyebrow">A little note from my heart</p><h2>You are so easy<br>to <em>celebrate.</em></h2><div class="birthday-banner"><small>Today and always</small><strong>Happy Birthday,<br>${name()}!</strong><div class="banner-hearts">♡　✦　♡　✦　♡</div></div><p class="finale-copy">${formatMessage(cfg.finalHeading)}</p><p class="lede">${formatMessage(cfg.finalMessage)}</p><div class="final-actions">${button("Keep this memory", "save-card", "button-gold")}${button("Secret room", "secret", "button-quiet")}${button("Close this memory", "close-memory", "button-quiet")}</div><button class="tiny-star" type="button" data-action="secret" aria-label="Open a hidden message">✦</button><div class="capsule"><strong>Birthday time capsule 🎁</strong><small>${capsuleText()}</small></div></section>`;
  }
  function capsuleText() { const unlock = new Date(cfg.birthday); if (Number.isNaN(unlock.getTime())) return "Add her birthday in js/config.js to start the countdown 🔒"; unlock.setFullYear(unlock.getFullYear() + 1); const days = Math.ceil((unlock - new Date()) / 86400000); const dateLabel = unlock.toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }); return days > 0 ? `Unlocks on ${dateLabel} · ${days} days 🔒` : (cfg.nextBirthdayMessage || "The time capsule is ready to open."); }
  function openMemory(index) { const memory = missionMemories[index]; progress.memories = [...new Set([...(progress.memories || []), index])]; saveProgress(); const image = memory.image ? `<img src="${esc(memory.image)}" alt="" loading="lazy" onerror="this.remove()">` : ""; document.getElementById("modal-root").innerHTML = `<div class="modal-backdrop" data-action="close-modal"><article class="modal-card" role="dialog" aria-modal="true"><button class="modal-close" data-action="close-modal" type="button" aria-label="Close">×</button>${image}<p class="eyebrow">Memory recovered</p><h3>${esc(memory.title)}</h3><span class="modal-date">${esc(memory.date)}</span><p>${esc(memory.description)}</p></article></div>`; }
  function openBalloonMessage(index) { const message = balloonMessages[index]; const image = message.image ? `<img src="${esc(message.image)}" alt="" loading="lazy" onerror="this.remove()">` : ""; document.getElementById("modal-root").innerHTML = `<div class="modal-backdrop" data-action="close-modal"><article class="modal-card balloon-message-card" role="dialog" aria-modal="true"><button class="modal-close" data-action="close-modal" type="button" aria-label="Close">×</button>${image}<p class="eyebrow">A little note for ${name()}</p><h3>${esc(message.category)}</h3><p>${esc(message.text)}</p><span class="heart-mark">♥</span></article></div>`; }
  function openLoveNote(index) { const notes = typeof loveNotes !== "undefined" ? loveNotes : [{ title: "You are deeply loved.", body: "Keep this one close." }]; const note = notes[index] || notes[0]; document.getElementById("modal-root").innerHTML = `<div class="modal-backdrop" data-action="close-modal"><article class="modal-card love-note-modal" role="dialog" aria-modal="true"><button class="modal-close" data-action="close-modal" type="button" aria-label="Close">×</button><p class="eyebrow">A tiny truth for ${name()}</p><div class="note-heart">♡</div><h3>${esc(note.title)}</h3><p>${esc(note.body)}</p></article></div>`; }
  function handleAnswer(choice) { const index = progress.questionIndex || 0; const question = missionQuestions[index]; const feedback = document.getElementById("answer-feedback"); if (choice === question.correct) { feedback.textContent = question.correctResponse; feedback.className = "feedback good"; progress.questionIndex = index + 1; saveProgress(); window.setTimeout(render, 650); } else { feedback.textContent = question.wrongResponses[Math.floor(Math.random() * question.wrongResponses.length)]; feedback.className = "feedback wrong"; playTone(160, 0.2); } }
  function handleKey(key) { let input = progress.vaultInput || ""; if (key === "⌫") input = input.slice(0, -1); else if (key === "↵") { if (input === cfg.vault.code) { toastMessage("Vault unlocked."); progress.vaultInput = ""; saveProgress(); window.setTimeout(() => go(4), 700); return; } progress.vaultFeedback = "That code is delightfully wrong. Try again."; input = ""; } else if (input.length < 3) input += key; progress.vaultInput = input; saveProgress(); renderVault(); }
  async function enableMic() { if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) { toastMessage("Looks like the birthday magic can't hear you 😄"); return; } try { micStream = await navigator.mediaDevices.getUserMedia({ audio: true }); const context = audioContext || new (window.AudioContext || window.webkitAudioContext)(); const source = context.createMediaStreamSource(micStream); const analyser = context.createAnalyser(); analyser.fftSize = 512; source.connect(analyser); const data = new Uint8Array(analyser.fftSize); let loudFrames = 0; const listen = () => { analyser.getByteTimeDomainData(data); let total = 0; data.forEach(value => { const delta = (value - 128) / 128; total += delta * delta; }); const volume = Math.sqrt(total / data.length); document.querySelector(".mic-status").textContent = `Listening... ${Math.round(volume * 100)}%`; document.querySelectorAll(".flames i").forEach(flame => { flame.style.transform = `scale(${1 + volume * 2}) rotate(${volume * 40 - 20}deg)`; }); if (volume > 0.18) loudFrames += 1; else loudFrames = Math.max(0, loudFrames - 1); if (loudFrames > 8) { stopMicrophone(); extinguishCandles(); return; } micFrame = requestAnimationFrame(listen); }; listen(); } catch (_) { toastMessage("Looks like the birthday magic can't hear you 😄"); } }
  function extinguishCandles() { document.querySelectorAll(".flames i").forEach((flame, index) => window.setTimeout(() => flame.classList.add("out"), index * 130)); window.setTimeout(() => { renderCelebration(); }, 900); }
  function secretRoom() { const room = cfg.secretRoom || { heading: "Things I like about you but rarely say", paragraphs: cfg.secretMessages || [] }; document.getElementById("modal-root").innerHTML = `<div class="modal-backdrop" data-action="close-modal"><article class="modal-card secret-card" role="dialog" aria-modal="true"><button class="modal-close" data-action="close-modal" type="button" aria-label="Close">×</button><p class="eyebrow">A little truth from my heart</p><h3>${esc(room.heading)}</h3><div class="secret-list">${room.paragraphs.map((message, index) => `<p style="--delay:${index * 120}ms">${esc(message)}</p>`).join("")}</div><strong class="capsule-title">${esc(cfg.capsule.heading)}</strong><p>${formatMessage(cfg.capsule.text)}</p><p>${esc(cfg.capsule.closing)}</p></article></div>`; }
  function drawWrappedText(ctx, text, x, y, maxWidth, lineHeight) { let line = ""; text.split(" ").forEach(word => { const test = `${line}${word} `; if (ctx.measureText(test).width > maxWidth && line) { ctx.fillText(line.trim(), x, y); line = `${word} `; y += lineHeight; } else line = test; }); if (line) ctx.fillText(line.trim(), x, y); return y; }
  function saveCard() { try { const canvas = document.createElement("canvas"); canvas.width = 1200; canvas.height = 1600; const ctx = canvas.getContext("2d"); const gradient = ctx.createLinearGradient(0, 0, 1200, 1600); gradient.addColorStop(0, "#fff8f0"); gradient.addColorStop(1, "#f1dce7"); ctx.fillStyle = gradient; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.textAlign = "center"; ctx.fillStyle = "#713d56"; ctx.font = "italic 36px Georgia"; ctx.fillText("A little birthday keepsake for", 600, 135); ctx.font = "bold 108px Georgia"; ctx.fillText(cfg.herName, 600, 275); ctx.fillStyle = "#d16f79"; ctx.font = "bold 64px Georgia"; ctx.fillText("HAPPY BIRTHDAY", 600, 445); ctx.font = "52px Georgia"; ctx.fillText("♡  ✦  ♡  ★  ♡", 600, 535); ctx.fillStyle = "#fff1e5"; ctx.strokeStyle = "#d89454"; ctx.lineWidth = 8; ctx.beginPath(); if (ctx.roundRect) ctx.roundRect(100, 650, 1000, 570, 32, 32); else ctx.rect(100, 650, 1000, 570); ctx.fill(); ctx.stroke(); ctx.fillStyle = "#bb704e"; ctx.font = "italic 31px Georgia"; ctx.fillText("If you ever come back to this little corner of the internet,", 600, 735); ctx.fillText("I hope it reminds you of one simple thing:", 600, 790); ctx.fillStyle = "#713d56"; ctx.font = "bold 38px Georgia"; drawWrappedText(ctx, "Someone wanted your birthday to feel as special as you make ordinary moments feel. ❤️", 600, 885, 850, 55); ctx.fillStyle = "#bb704e"; ctx.font = "italic 30px Georgia"; ctx.fillText("Made with a little effort, a lot of thought,", 600, 1340); ctx.fillText("and perhaps a little more care than I’ll admit. 😉", 600, 1395); ctx.font = "italic 34px Georgia"; ctx.fillText("with love, always", 600, 1490); canvas.toBlob(blob => { if (!blob) throw new Error("Canvas unavailable"); const file = new File([blob], "birthday-card.png", { type: "image/png" }); if (navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) navigator.share({ title: `Happy birthday, ${cfg.herName}`, files: [file] }).catch(() => {}); else { const link = document.createElement("a"); link.download = "birthday-card.png"; link.href = URL.createObjectURL(blob); link.click(); URL.revokeObjectURL(link.href); } }, "image/png"); } catch (_) { toastMessage("This browser could not export the card, but the memory is still yours."); } }
  function renderDevPanel() { if (!location.search.includes("dev=true")) return; const panel = document.getElementById("dev-panel"); panel.hidden = false; panel.innerHTML = `<strong>DEV MODE</strong>${sceneNames.map((entry, index) => `<button type="button" data-action="jump" data-scene="${index}">${String(index + 1).padStart(2, "0")} ${entry}</button>`).join("")}<button type="button" data-action="reset">Reset</button>`; }
  function showResume() { document.getElementById("modal-root").innerHTML = `<div class="modal-backdrop"><article class="modal-card resume-card" role="dialog" aria-modal="true"><p class="eyebrow">Signal found</p><h3>Resume your mission?</h3><p>Your last transmission is still waiting at ${esc(sceneNames[scene] || "the next scene")}.</p>${button("Resume", "resume", "button-gold")}${button("Start again", "start-again", "button-quiet")}</article></div>`; }
  document.addEventListener("click", event => { const target = event.target.closest("[data-action]"); if (!target) return; const action = target.dataset.action; if (action === "accept") { setupAudio(); playTone(620); go(1); } else if (action === "resume") { document.getElementById("modal-root").innerHTML = ""; render(); } else if (action === "start-again") { progress = {}; cakeSelections = [0, 1, 2, 3]; saveProgress(); document.getElementById("modal-root").innerHTML = ""; scene = 0; render(); } else if (action === "answer") handleAnswer(Number(target.dataset.choice)); else if (action === "continue-identity") go(2); else if (action === "memory") openMemory(Number(target.dataset.index)); else if (action === "continue-memories") go(3); else if (action === "hint") toastMessage("Follow the glowing signals. The next step is waiting."); else if (action === "clue") toastMessage(cfg.vault.clues[Number(target.dataset.index)]); else if (action === "key") handleKey(target.dataset.key); else if (action === "continue-cake") go(5); else if (action === "wish-made") renderBlowPrompt(); else if (action === "enable-mic") enableMic(); else if (action === "tap-blow") extinguishCandles(); else if (action === "start-balloons") renderBalloons(); else if (action === "balloon") { const index = Number(target.dataset.index); if ((progress.balloons || []).includes(index)) return; progress.balloons = [...new Set([...(progress.balloons || []), index])]; saveProgress(); const msg = balloonMessages[index]; toastMessage(`${msg.category}: ${msg.text}`); target.classList.add("popped"); const opened = progress.balloons.length; const counter = document.querySelector(".balloons-scene .counter"); if (counter) counter.textContent = `${opened} / ${balloonMessages.length} messages discovered`; if (opened === balloonMessages.length) { const continueButton = document.querySelector(".balloons-scene [data-action='hint']"); if (continueButton) { continueButton.dataset.action = "continue-balloons"; continueButton.textContent = "Continue"; continueButton.classList.add("button-gold"); } } } else if (action === "continue-balloons") go(7); else if (action === "open-letter") renderOpenedLetter(); else if (action === "continue-letter") go(8); else if (action === "play-song") { setupAudio(); playMusic(cfg.audio.birthdaySong); document.getElementById("song-status").textContent = "Now playing your song. Missing files are okay; the mission remains intact."; } else if (action === "continue-song") go(9); else if (action === "save-card") saveCard(); else if (action === "secret") secretRoom(); else if (action === "close-modal" && (event.target === target || target.classList.contains("modal-close"))) { document.getElementById("modal-root").innerHTML = ""; if (scene === 2) render(); } else if (action === "jump") go(Number(target.dataset.scene)); else if (action === "reset") { try { localStorage.removeItem(storageKey); } catch (_) {} location.reload(); } });
  document.addEventListener("change", event => { if (event.target.matches("[data-action='tier']")) { cakeSelections[Number(event.target.dataset.tier)] = Number(event.target.value); progress.cakeSelections = cakeSelections; saveProgress(); renderCake(); } });
  document.addEventListener("click", event => { const balloon = event.target.closest("[data-action='balloon']"); if (balloon) openBalloonMessage(Number(balloon.dataset.index)); const note = event.target.closest("[data-action='love-note']"); if (note) { note.classList.add("revealed"); openLoveNote(Number(note.dataset.index)); } const startBalloons = event.target.closest("[data-action='start-balloons']"); if (startBalloons) { scene = 3; progress.scene = 3; saveProgress(); updateHud(); } const closeMemory = event.target.closest("[data-action='close-memory']"); if (closeMemory) { stopMusic(); stage.innerHTML = `<section class="scene centered-scene closed-memory"><div class="seal">♡</div><p class="eyebrow">Memory kept</p><h2>Keep this little<br><em>happiness.</em></h2><p class="lede">You can come back whenever you need a little reminder of how loved you are.</p></section>`; } const closeModal = event.target.closest("[data-action='close-modal']"); if (closeModal && scene === 3 && (progress.balloons || []).length === balloonMessages.length) go(4); });
  audioToggle.addEventListener("click", () => { if (activeAudio) { activeAudio.muted = !activeAudio.muted; audioToggle.textContent = activeAudio.muted ? "×" : "♫"; } else toastMessage("Sound will begin after the next audio action."); });
  function boot() { let value = 0; const labels = ["Loading memories...", "Preparing cake...", "Calibrating happiness...", "Locating birthday girl..."]; const timer = window.setInterval(() => { value += 25; bar.style.width = `${value}%`; label.textContent = labels[Math.min(labels.length - 1, value / 25 - 1)]; if (value >= 100) { window.clearInterval(timer); window.setTimeout(() => { loading.classList.add("hidden"); renderDevPanel(); updateHud(); if (scene > 0 && !location.search.includes("dev=true")) showResume(); else render(); }, 450); } }, 120); }
  boot();
})();
